# примеры API-запросов


# создание продукта
POST http://localhost:8000/api/v1/products/
Content-Type: application/json

{
  "title": "Помимидор",
  "description": "Лучшие помидоры на рынке"
}

###

# получение продуктов
GET http://localhost:8000/api/v1/products/
Content-Type: application/json

###

